### PR TITLE
Update pntr and switch to nearest neighbor filter

### PR DESCRIPTION
**Pull request by RobLoach**

### CODE REVIEW

**Comment by konsumer** [comment]
damn, I did same nearest-neighbor and alphabetized the functions before seeing this PR, so it makes a tricky merge-conflict.

**Comment by RobLoach** [comment]
Haha, if it's working,then 😁

**Comment by konsumer** [comment]
I may have merged wrong, but I am also getting some undefined symbols.

```
Undefined symbols for architecture x86_64:
  "_pntr_load_font_bmf", referenced from:
      _NimMainModule in @mtest_pntr.nim.c.o
  "_pntr_load_font_bmf_from_memory", referenced from:
      _NimMainModule in @mtest_pntr.nim.c.o
  "_pntr_load_font_ttf", referenced from:
      _NimMainModule in @mtest_pntr.nim.c.o
  "_pntr_load_font_ttf_from_memory", referenced from:
      _NimMainModule in @mtest_pntr.nim.c.
```

I'd like to get your API changes in, so I will try to merge the differences, manually.

**Comment by konsumer** [comment]
I think I got it all merged. Thanks for the update.

**Pull request closed without merging**
